#+title: White Chocolate Macadamia

A Haskell Stack template for a cookie cutter project.

* Features

** =macadamia.hsfiles=

- Single executable
- MIT license (which is also the license used by default)

** =macadamia-matplotlib.hsfiles=

- Single executable
- MIT license (which is also the license used by default)
- Example using =matplotlib= for visualisation

** =macadamia-hspec.hsfiles=

- Single executable
- MIT license (which is also the license used by default)
- Example using =hspec= for testing

* Usage 

To create a new stack project with this template use the following

#+begin_src sh
stack new my-project <url/for.hsfiles> 
#+end_src

For example

- =https://raw.githubusercontent.com/aezarebski/white-chocolate-macadamia/main/macadamia.hsfiles=
- =https://raw.githubusercontent.com/aezarebski/white-chocolate-macadamia/main/macadamia-matplotlib.hsfiles=
- =https://raw.githubusercontent.com/aezarebski/white-chocolate-macadamia/main/macadamia-hspec.hsfiles=

In case you have not set up your stack configuration file, at =~/.stack/config=,
you can still provide details when starting the new project. For example you
might add you name by appending =-p "author-name:Alexander E. Zarebski"= to the
end of the command above. If you want this to create the project in the current
directory, add the =--bare= flag after the project name and before the URL.

The project template has downloaded use the following commands to check
everything is working correctly. The setup step may take a while if you need to
download GHC.

#+begin_src sh
stack setup                     # this may take a couple of minuts
stack build
stack run
#+end_src
